Main group 2 create button shopping-cart
tryber/sd-06-project-frontend-online-store pull request #193
Opened 2020-09-30 20:07 UTC by rafMewtwo

2020-09-30 20:25 UTC, ailsonjr approved these changes
I didn't find any error or point to be improved, being ready to merge

2020-10-01 14:01 UTC, HCaetano commented on src/pages/Home.jsx
> +          <input id="search-input" />
oi, @rafMewtwo! acredito que esteja faltando o `type` deste `input` aqui, concorda?

```suggestion
          <input type="text" id="search-input" />
```

2020-10-01 14:04 UTC, HCaetano commented on src/pages/Home.jsx
> +        <Link to="/cart" data-testid="shopping-cart-button"><img src={ cart } alt="imagem cart" width="30px"/></Link>
oi, @rafMewtwo! aqui o atributo `alt` está com a palavra "imagem" em português. além disso, o component `Link` está com um estilo `inline` em vez de usá-lo a partir de um arquivo `.css`. você poderia refatorar, por favor?

2020-10-01 14:05 UTC, HCaetano commented on src/pages/ShoppingCart.jsx
> +                <Link to="/"><img src={ back } alt="imagem voltar" width="30px" /></Link>
oi, @rafMewtwo! aqui e nas linhas 13 e 16 temos aquela questão do alt com mensagem em português e estilo inline no componente

2020-10-01 14:10 UTC, HCaetano commented on src/pages/ShoppingCart.jsx
> +                <br />
eu acredito que esse elemento hoje em dia não é muito recomendado para gerar espaço visual, mas sim para quebrar linhas de texto, pelo que eu pude ver [aqui](https://stackoverflow.com/questions/1726073/is-it-sometimes-bad-to-use-br). faz sentido pra ti?

se você achar uma boa, eu sugeriria gerar esse espaçamento entre os elementos utilizando css. como conversamos ontem, estética não é uma prioridade, então não haveria muito problema deixar o br aí agora. poderíamos tirá-los depois dos 100%, na hora de fazer o estilo certinho

2020-10-01 14:12 UTC, HCaetano commented on src/pages/Home.jsx
> +import cart from './../img/cart.png'
boa! criou a pasta para colocar as imagens :))

2020-10-01 14:12 UTC, HCaetano commented on src/pages/Home.jsx
>  import React, { Component } from 'react';
eu também gosto de descontruir o Component em vez de usar React.Component na declaração da classe :)

2020-10-01 14:13 UTC, HCaetano commented on src/pages/ShoppingCart.jsx
> +import back from './../img/back.png';
o que seria essa imagem "back"?

2020-10-01 14:15 UTC, HCaetano requested changes
oi, rafael! parabéns! eu não sou muto bom com Links, fico feliz que tenhas conseguido resolver o requisisto! apesar de eu ter feito um bom número de observações, espero que não pareça que estou implicando contigo hehe. tentei só apontar algumas coisas em relação aos combinados que fizemos e boas práticas

2020-10-01 18:37 UTC, rafMewtwo commented on src/pages/ShoppingCart.jsx
> +                <Link to="/"><img src={ back } alt="imagem voltar" width="30px" /></Link>
conforme os acordos em chamada, mantem o alt p/ acessibilidade em pt-br

2020-10-01 18:38 UTC, rafMewtwo commented on src/pages/ShoppingCart.jsx
> +import back from './../img/back.png';
a imagem vai ser renomeada para goHome

2020-10-01 19:48 UTC, HCaetano approved these changes
Boa! Obrigado pelas refatorações

2020-10-01 19:58 UTC, merged