[Group 18] - Req 6
tryber/sd-06-project-frontend-online-store pull request #285
Opened 2020-10-01 22:52 UTC by mcoutinho88

2020-10-02 17:21 UTC, cleytonoliveira requested changes
Ficou muito bom @mcoutinho88 e @ilanribeiro, código ficou bem limpo e com a lógica muito boa. Realizei algumas sugestões, vejam o que acham.

2020-10-02 17:21 UTC, cleytonoliveira commented on src/components/SearchEngine.js
>          <ShoppingCartButton />
Acredito que faz mais sentido se o botão de Pesquisar ficar antes de ShoppingCartButton, não acham?

2020-10-02 17:21 UTC, cleytonoliveira commented on src/components/SearchEngine.js
> +          onClick={ () => onClick(this.state) }
Fiquei um pouco confuso em entender o que esta sendo usado no onClick, seria o queryInput mesmo?

2020-10-02 17:21 UTC, cleytonoliveira commented on src/pages/Home/Home.js
> +      }
Será que precisa desta lógica em categorias? Sabendo que as categorias se tratam de vários produtos? Acredito que dificilmente terá uma categoria sem produtos.

2020-10-03 03:34 UTC, mcoutinho88 commented on src/App.js
> +import Home from './pages/Home/Home';
Boa sugestão @cleytonoliveira, podemos fazer isso na hora de fazer o merge ou então deixamos para o próximo requisito. A intenção da estrutura que fiz foi criar uma pasta com o nome da pagina, e deixar o css referente a pagina na mesma pasta. Acho que ficaria mais organizado talvez se deixarmos todos css na mesma pasta como vc sugeriu

2020-10-03 03:35 UTC, mcoutinho88 commented on src/components/ListCategory.js
> +            </label>
O input seria trocado pelo Link? Não entendi direito (não vi os outros requisitos kkkk)

2020-10-03 03:36 UTC, mcoutinho88 commented on src/components/SearchEngine.js
>      // had to do this to bypass lint rule (no-magic-number).. go figure..
Não, esqueci de retirar kkkk

2020-10-03 03:38 UTC, mcoutinho88 commented on src/components/ProductList.js
> +          && products.results.map((prod) => (
Pode ser. Deixei prod pois é uma forma encurtada de produto, mas podemos trocar caso todo mundo concorde

2020-10-03 03:40 UTC, mcoutinho88 commented on src/components/SearchEngine.js
> +          onClick={ () => onClick(this.state) }
Sim, poderia passar direto o queryInput. Eu fiz essa linha quando tinha os outros estados e como retirei os estados em seguida, acabei não refatorando essa parte

2020-10-03 03:40 UTC, mcoutinho88 commented on src/components/SearchEngine.js
>          <ShoppingCartButton />
Sim, concordo

2020-10-03 03:41 UTC, mcoutinho88 commented on src/pages/Home/Home.js
> +      }
Verdade, essa parte eu copiei da lógica da pesquisa por termos kkkk

2020-10-03 10:55 UTC, ilanribeiro approved these changes

2020-10-03 10:55 UTC, ilanribeiro commented on src/App.js
> +import Home from './pages/Home/Home';
@cleytonoliveira achei a sugestão bacana. Acredito que para esse tamanho de projeto dá pra fazer assim tranquilamente. Lembrei de uma sugestão feita pelo Murilo Wolf em um dos fechamentos, sobre essa questão de arquitetura. Fui pesquisar e achei uma explicação bem legal nesse artigo aqui:  https://www.sitepoint.com/react-architecture-best-practices/ No primeiro tópico, sobre arquitetura em projetos React.

2020-10-03 11:14 UTC, ilanribeiro commented on src/components/ProductList.js
> +          && products.results.map((prod) => (
A ideia é interessante @cleytonoliveira. Eu geralmente costumo utilizar os termos como plural, antes do map, e como singular, após o map. Faço isso apenas para ficar claro que estou individualizando o elemento do array a partir daquele ponto. Entendo que utilizar o termo 'item' também daria essa ideia de individualização, mas será que não ficaria mais genérico do que utilizar 'product', por exemplo?

2020-10-05 18:18 UTC, cleytonoliveira approved these changes

2020-10-05 18:28 UTC, merged